# Generated by Django 3.2 on 2025-11-25 02:23

from django.db import migrations, models
import django.utils.timezone
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('continent', models.CharField(max_length=50)),
                ('results_json', djongo.models.fields.JSONField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('coordinates_str', models.CharField(default='N/A', max_length=50)),
            ],
            options={
                'db_table': 'weather_entries',
            },
        ),
    ]
